version: '3.5'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: typoteka-users
    ports:
      - 27018:27017
    volumes:
      - ./db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/typoteka-users --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  mongodb-express:
    image: mongo-express
    depends_on:
      - mongodb
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@mongodb:27017/

  typoteka.users:
    image: typoteka.users
    depends_on:
      - mongodb
    restart: always
    container_name: typoteka.users
    ports:
      - 3335:3333
    environment:
      PORT: 3335
      MONGO_DB: typoteka-users
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: test
      MONGO_AUTH_BASE: admin
      JWT_SECRET: secret
      RABBIT_USER: admin
      RABBIT_PASSWORD: test
      RABBIT_HOST: rabbitmq:5672
      RABBIT_USERS_SERVICE_QUEUE: typoteka.subscribers
